### ISSUE TITLE
Command overrides don't support colon in value

### ISSUE THREAD

**Issue by chadmyers** [FubuMvcArchive/bottles#15]
Given the following command line:
``C:\hudson\workspace\StoryTeller>package\bottlerunner.exe deploy -profile assets -deployment package\deployment -override root:\blue-assets`

I want to say:
`-override root:c:\blue-assets`

but it fails because the code does a split on the `:` character.

**Comment by drusellers** [comment]
@chadmyers is this a CLI issue or a Bottles / Milkman issue?
