### ISSUE TITLE
Merge the Bottles.Tools nuget with Bottles?

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/bottles#27]
Anybody object?  And while we're at it, make sure that this nuget is made with the right source of the Bottles.dll that ilmerges the Ionic.Zip.dll file?  Strong name problems are still killing us with ripple local

**Comment by jmarnold** [comment]
+1 This has always been annoying

**Comment by drusellers** [comment]
pretty sure this is done now right?

**Comment by jeremydmiller** [comment]
Yup.
 Jeremy D. Miller
The Shade Tree Developer
jeremydmiller@yahoo.com

---

From: Dru Sellers 
reply@reply.github.com

To: Jeremy D. Miller jeremydmiller@yahoo.com
Sent: Mon, July 30, 2012 2:10:26 PM
Subject: Re: [bottles] Merge the Bottles.Tools nuget with Bottles? (#27)

pretty sure this is done now right?

---

**Comment by drusellers** [comment]
this is done
