### ISSUE TITLE
Evaluate Merging PackageManifest class and PackageInfo class

### ISSUE THREAD

**Issue by drusellers** [FubuMvcArchive/bottles#29]
This one is going to be tricky. This was caught by IPackageInfo not giving easy access to the ConfigFileSet. That is my real goal.

**Comment by jeremydmiller** [comment]
Are you sure you wanna do that?  PackageManifest is meant to be serializable 
just for ease of use.  Merging would just make all that harder.  What if you 
just made the ctor of PackageInfo be:

new PackageInfo(string packageDirectory, PackageManifest manifest)
 Jeremy D. Miller
The Shade Tree Developer
jeremydmiller@yahoo.com

---

From: Dru Sellers 
reply@reply.github.com

To: Jeremy D. Miller jeremydmiller@yahoo.com
Sent: Tue, April 24, 2012 2:40:11 PM
Subject: [bottles] Evaluate Merging PackageManifest class and PackageInfo class 
(#29)

This one is going to be tricky. This was caught by IPackageInfo not giving easy 
access to the ConfigFileSet. That is my real goal.

---

Reply to this email directly or view it on GitHub:
https://github.com/DarthFubuMVC/bottles/issues/29

**Comment by drusellers** [comment]
I do not want to do that. When I opened the issue I thought I did though. I wanted the issue to track my real issue which was getting at the ConfigFileSet. +1 on keeping PackageManifest as the thing it is currently. I think its enriching PackageInfo / PackageManifestReader.

I am working on a good test to run with before I actually make any changes. Lots 'o spelunking at the moment.

**Comment by drusellers** [comment]
IPackageInfo.ForFolder just gives you a path to the 'Folder' but in the use case, I am trying to get access to the files specified in the 'ConfigFileSet' I am in the right section of code, now just trying to figure out how to make it work and come together. :)

**Comment by jeremydmiller** [comment]
If you make PackageInfo aware of PackageManifest you've got everything you could 
possibly need and PackageManifestReader gets real simple fast.
 Jeremy D. Miller
The Shade Tree Developer
jeremydmiller@yahoo.com

---

From: Dru Sellers 
reply@reply.github.com

To: Jeremy D. Miller jeremydmiller@yahoo.com
Sent: Tue, April 24, 2012 3:14:06 PM
Subject: Re: [bottles] Evaluate Merging PackageManifest class and PackageInfo 
class (#29)

I do not want to do that. When I opened the issue I thought I did though. I 
wanted the issue to track my real issue which was getting at the ConfigFileSet. 
+1 on keeping PackageManifest as the thing it is currently. I think its 
enriching PackageInfo / PackageManifestReader.

I am working on a good test to run with before I actually make any changes. Lots 
'o spelunking at the moment.

---

**Comment by drusellers** [comment]
Agreed. I am just playing around right now, but I think injecting the
manifest into the IPackageInfo is going to be a win.

i.e. composition baby. :)

-d

On Tue, Apr 24, 2012 at 15:15, Jeremy D. Miller <
reply@reply.github.com

**Comment by drusellers** [comment]
Do you recall what you were wanting to change here? I know you have slept since then, but want to ask anyways. https://github.com/DarthFubuMVC/bottles/blob/master/src/Bottles/PackageManifestReader.cs#L30

**Comment by jeremydmiller** [comment]
Pretty sure that's just about your idea of folders being extensible.  I think 
you'd just have PackageInfo interrogate PackageManifest to get that data from 
now on.  I don't see us ever having a package where the data is on the C:\ drive 
and the webcontent is on a share somewhere.
 Jeremy D. Miller
The Shade Tree Developer
jeremydmiller@yahoo.com

---

From: Dru Sellers 
reply@reply.github.com

To: Jeremy D. Miller jeremydmiller@yahoo.com
Sent: Tue, April 24, 2012 3:21:14 PM
Subject: Re: [bottles] Evaluate Merging PackageManifest class and PackageInfo 
class (#29)

Do you recall what you were wanting to change here? I know you have slept since 
then, but want to ask anyways. 
https://github.com/DarthFubuMVC/bottles/blob/master/src/Bottles/PackageManifestReader.cs#L30

---

**Comment by drusellers** [comment]
I would agree with that. Just trying to figure out how I want to attack it. So far, its going pretty well.

**Comment by jeremydmiller** [comment]
Jeremy says "No".  Different roles.
