### ISSUE TITLE
WebContent should be renamed to Content(?)

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/bottles#3]
I think we need to consider this.

**Comment by drusellers** [comment]
To what degree do we want to make the package manifest a little more flexible? the folders are currently pretty hard coded. what if I want a 'messages' folder to do special stuff with? That said, I don't think there is anything wrong with the well known folders being standardized and having easy methods on them.

**Comment by jeremydmiller** [comment]
I vote no.  You can make it smart enough to look for either Content or WebContent to keep it backwards compatible, but otherwise I say no way this change creates enough/any value to justify doing it.

**Comment by drusellers** [comment]
Is this a vote of no to the issue that you made or to my comment?

**Comment by jeremydmiller** [comment]
To be very clear, I'm vetoing any change that would render an existing Bottle 
inoperable, period.  The change from WebContent to Content is not remotely 
important or valuable enough in my opinion to even consider this change.  If you 
_want_ to make WebContent and Content be interchangeable in Bottles internals, 
fine, but that just adds complexity to the internals.

---

From: Dru Sellers 
reply@reply.github.com

To: Jeremy D. Miller jeremydmiller@yahoo.com
Sent: Wed, August 1, 2012 9:13:58 AM
Subject: Re: [bottles] WebContent should be renamed to Content(?) (#3)

Is this a vote of no to the issue that you made or to my comment?

---

**Comment by drusellers** [comment]
Ok, so I am going to change the folder name to Content and support WebContent, but I will output a warning that it should be renamed. Note this isn't going to happen right away, I just want to get my thoughts together for when I make the change.

**Comment by jeremydmiller** [comment]
I like that.  Are you thinking any more about making the folders extensible underneath the Bottle structure?  I don't have any kind of need for that in the near future, but someday...

**Comment by drusellers** [comment]
Let me make an issue for that so we can both track our thoughts. :)

**Comment by jeremydmiller** [comment]
I'm permanently scrapping this one.  In almost 2 years of work, this just hasn't mattered.
