### ISSUE TITLE
BottleRunner.exe 'target' option for 'create' command is limited to Debug|Release

### ISSUE THREAD

**Issue by hartez** [FubuMvcArchive/bottles#33]
The '-target' option for the 'create' command in BottleRunner.exe only allows 'Debug' or 'Release', which means that other project configurations can't be targeted.

Ideally, any valid compilation target for the assemblies being packaged could be targeted.

**Comment by jeremydmiller** [comment]
Wanna just go do the pull request for it?  You just need to change it from the enum to a string in the command

**Comment by hartez** [comment]
I figured I would if no one else picks it up before I get some breathing room on my current project. This is mostly just a stake in the ground so it doesn't get forgotten.
