### ISSUE TITLE
assembly-pak, other package commands cannot blow up if Exclude directory does not exist

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/bottles#38]
Set up an assembly package with the default PackageManifest that excludes "data/_._", but with no /data folder.  Today this blows up.

**Comment by drusellers** [comment]
derp. this should be easy to fix I think. Thank you for logging it.

On Fri, Jul 27, 2012 at 9:10 AM, Jeremy D. Miller <
reply@reply.github.com

**Comment by jeremydmiller** [comment]
Fixed quite a while ago with a FubuCore change
