### ISSUE TITLE
Extensible Bottle File Structure

### ISSUE THREAD

**Issue by drusellers** [FubuMvcArchive/bottles#41]
Currently the bottle file structure is quite rigid, and should be more dynamic. However this is going to be a larger change that I think I want to happen as a part of the Bottles 2.0 push. It will stream line the code and allow more extensibility but I want to have a clear demarcation to help support people moving from old to new.

right now the folders are hard coded into easy to access for the programmer properties. I am thinking of easy ways that can be use to assist the programmer and the people that use them. I will put thoughts here as I ponder the issue.

**Comment by jeremydmiller** [comment]
Hasn't come up as a need.  Going backwards instead to make bottles easier to use.
